export const ALLIANCE_ENEMY = -2;
export const ALLIANCE_UNFRIENDLY = -1;
export const ALLIANCE_NEUTRAL = 0;
export const ALLIANCE_FRIENDLY = 1;
export const ALLIANCE_ALLY = 2;
export const ALLIANCES_ALL = [ALLIANCE_ENEMY, ALLIANCE_UNFRIENDLY, ALLIANCE_NEUTRAL, ALLIANCE_FRIENDLY, ALLIANCE_ALLY];

export const MY_USERNAME = "Winseven4lyf_";
